### ISSUE TITLE
Bizarre Crash

### ISSUE THREAD

**Issue by evanbones** [spoorn/sodium-forge#132]
Can't reproduce, doesn't affect any of my friends saving the same pack. Happens completely randomly it seems like. Maybe it's related to the Lucent crash?

[03Aug2021 23:10:18.341] [Render thread/FATAL] [net.minecraft.client.Minecraft/]: Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: -1
	at it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.rehash(Long2ReferenceOpenHashMap.java:1063) ~[fastutil-8.2.1.jar:?]
	at it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.insert(Long2ReferenceOpenHashMap.java:272) ~[fastutil-8.2.1.jar:?]
	at it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.put(Long2ReferenceOpenHashMap.java:280) ~[fastutil-8.2.1.jar:?]
	at me.jellysquid.mods.sodium.client.world.cloned.ClonedChunkSectionCache.createSection(ClonedChunkSectionCache.java:49) ~[sodium:2.9.10+rev.ea6353c]
	at me.jellysquid.mods.sodium.client.world.cloned.ClonedChunkSectionCache.acquire(ClonedChunkSectionCache.java:27) ~[sodium:2.9.10+rev.ea6353c]
	at me.jellysquid.mods.sodium.client.world.WorldSlice.prepare(WorldSlice.java:143) ~[sodium:2.9.10+rev.ea6353c]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.createRebuildTask(ChunkBuilder.java:265) ~[sodium:2.9.10+rev.ea6353c]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.scheduleRebuildTaskAsync(ChunkBuilder.java:255) ~[sodium:2.9.10+rev.ea6353c]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.deferRebuild(ChunkBuilder.java:236) ~[sodium:2.9.10+rev.ea6353c]
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:487) ~[sodium:2.9.10+rev.ea6353c]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:226) ~[sodium:2.9.10+rev.ea6353c]
	at net.minecraft.client.renderer.WorldRenderer.redirect$bbl000$setupTerrain(WorldRenderer.java:5767) ~[?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:936) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]

**Comment by evanbones** [comment]
Ok, it's almost definitely related to Lucent. My friends all later experienced this same crash

**Comment by evanbones** [comment]
I will say though, it is far more playable. It seems to randomly crash every hour or so opposed to every 10 seconds as it was before
