### ISSUE TITLE
Possible conflict with FTB Chunks in MC 1.16.5

### ISSUE THREAD

**Issue by FatalRex** [spoorn/sodium-forge#164]
Hello, very impressed with this mod!

Thank you for such a great job making my minecraft playable again after getting rid of optifine and going with this.

I did however get a crash upon installing sodium-forge with the FTB-chunks mod.

I'll be hitting up the FTB chunks github as well with this but I thought both parties would benefit.

the exit code was -1 and it said FTB chunks was the culprit in the message on the launcher.

Here's the report if you need the whole thing :
[crash-2021-08-31_04.50.05-client.txt](https://github.com/spoorn/sodium-forge/files/7084767/crash-2021-08-31_04.50.05-client.txt)

but here's the part i saw as important : 

Time: 8/31/21 4:50 AM
Description: Unexpected error

java.lang.NoClassDefFoundError: com/feed_the_beast/mods/ftbchunks/client/FTBChunksClient
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkAdded(SodiumWorldRenderer.java:342) ~[?:2.1] {re:mixin,re:classloading}
	at me.jellysquid.mods.sodium.client.world.SodiumChunkManager.onChunkLoaded(SodiumChunkManager.java:198) ~[?:2.1] {re:mixin,re:classloading}
	at me.jellysquid.mods.sodium.client.world.SodiumChunkManager.func_228313_a_(SodiumChunkManager.java:125) ~[?:2.1] {re:mixin,re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147263_a(ClientPlayNetHandler.java:726) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:ftbchunks-common.mixins.json:ClientPacketListenerMixin,pl:mixin:APP:valhelsia_core.mixins.json:client.ClientPlayNetHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}

Thanks again for all your hard work, this mod is a lifesaver. 5-20 FPS to 130 FPS.. can't say enough how much this has made a difference. 

Cheers!

**Comment by FatalRex** [comment]
P.S.

Aparently the FTB team is saying this mod is reliant on a heavily out-dated version of FTBchunks.
Is this true? and what version would I require to get this to run properly?

**Comment by FatalRex** [comment]
Update : Please close this issue, I was aparently guided to an old version of sodium and have now updated and all is working.

Apologies and thanks.

**Comment by FlameyFaucet** [comment]
There's a little close issue button next to the comment button ;P

**Comment by FatalRex** [comment]
haha, thanks!
