### ISSUE TITLE
Mixin structures

### ISSUE THREAD

**Issue by StrangerSon71** [spoorn/sodium-forge#34]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

1. Download Modlist
2. Launch game
3. The game crashes

### Crash Report File
For some reason there's no crash report, don't know why
### [Optional] Server/Client logs
Mixin apply failed sodium.mixins.json:gen.features.StructureFeatureMixin -> net.minecraft.world.gen.feature.structure.Structure: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/gen/feature/structure/Structure::biomeConditionalGetChunk with priority 1000 cannot inject into net/minecraft/world/gen/feature/structure/Structure::func_236388_a_(Lnet/minecraft/world/IWorldReader;Lnet/minecraft/world/gen/feature/structure/StructureManager;Lnet/minecraft/util/math/BlockPos;IZJLnet/minecraft/world/gen/settings/StructureSeparationSettings;)Lnet/minecraft/util/math/BlockPos; merged by com.performant.coremod.mixin.world.StructureMixin with priority 1000 [PREINJECT Applicator Phase -> sodium.mixins.json:gen.features.StructureFeatureMixin -> Prepare Injections ->  -> redirect$zgf000$biomeConditionalGetChunk(Lnet/minecraft/world/IWorldReader;IILnet/minecraft/world/chunk/ChunkStatus;)Lnet/minecraft/world/chunk/IChunk; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/gen/feature/structure/Structure::biomeConditionalGetChunk with priority 1000 cannot inject into net/minecraft/world/gen/feature/structure/Structure::func_236388_a_(Lnet/minecraft/world/IWorldReader;Lnet/minecraft/world/gen/feature/structure/StructureManager;Lnet/minecraft/util/math/BlockPos;IZJLnet/minecraft/world/gen/settings/StructureSeparationSettings;)Lnet/minecraft/util/math/BlockPos; merged by com.performant.coremod.mixin.world.StructureMixin with priority 1000 [PREINJECT Applicator Phase -> sodium.mixins.json:gen.features.StructureFeatureMixin -> Prepare Injections ->  -> redirect$zgf000$biomeConditionalGetChunk(Lnet/minecraft/world/IWorldReader;IILnet/minecraft/world/chunk/ChunkStatus;)Lnet/minecraft/world/chunk/IChunk; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.registries.GameData.init(GameData.java:178)
	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:132)
	at net.minecraft.util.registry.Registry.forge(Registry.java:347)
	at net.minecraft.util.registry.Registry.forge(Registry.java:331)
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:140)
	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
15:32:06.785
Process crashed with exit code 1

### Mods list
Iabnormals_core-1.16.5-3.1.1.jar
abnormals_delight-1.16.5-1.1.1.jar
Abundance-1.16.5-1.0.5.jar
AI-Improvements-1.16.2-0.3.0.jar
alexsmobs-1.10.1.jar
allurement-1.16.5-1.2.0.jar
antiqueatlas-5.4.4-forge.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
archers_paradox-1.16.4-1.2.0.jar
Artifacts-1.16.5-2.9.3.jar
atmospheric-1.16.5-3.1.0.jar
AutoRegLib-1.6-49.jar
autumnity-1.16.5-2.1.1.jar
Bayou-Blues-1.16.5-1.0.5.jar
berry_good-1.16.5-4.1.1.jar
Better-Badlands-1.16.5-2.0.3.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
BetterStrongholds-1.16.4-1.1.jar
bgcore-1.16.5-3.2.jar
buzzier_bees-1.16.5-3.0.1.jar
caelus-forge-1.16.5-2.1.3.0.jar
CavesAndCliffsBackport-1.16.5-5.2.jar
citadel-1.7.1-1.16.5.jar
cobbler-1.6.1.jar
cofh_core-1.16.4-1.2.1.jar
comforts-forge-1.16.5-4.0.0.4.jar
cookielicious-1.16.5-1.2.2.jar
CraftTweaker-1.16.5-7.1.0.314.jar
create-mc1.16.5_v0.3.1c.jar
curioofundying-forge-1.16.5-5.2.0.0.jar
curios-forge-1.16.5-4.0.5.2.jar
curiouselytra-forge-1.16.5-4.0.2.3.jar
DarkerDepths-1.16.5-1.0.1.jar
dungeonsarise1.16.5-1.2.72a.jar
endergetic-1.16.4-3.0.0.jar
Enhanced-Mushrooms-1.16.5-3.0.8.jar
environmental-1.16.5-1.0.0.jar
expandability-2.0.1-forge.jar
extraboats-1.16.5-2.1.0.jar
FarmersDelight-1.16.5-0.4.3.jar
FastFurnace-1.16.4-4.4.0.jar
FastLeafDecay-v25.jar
FastWorkbench-1.16.4-4.5.1.jar
Fruitful-1.16.5-2.1.0.jar
geckolib-forge-1.16.5-3.0.41.jar
iceandfire-2.1.7-1.16.5.jar
infernal-expansion-forge-1.3.jar
jei-1.16.5-7.7.0.106.jar
JEITweaker-1.16.5-1.0.1.31.jar
Jellyfishing-1.6.9.jar
majrusz-library-1.16.4-2.0.0.jar
majruszs-difficulty-1.16.4-1.0.0.jar
mgui-1.16.5-3.2.0.jar
minecolonies-0.14.221-BETA-universal.jar
MoreJellyfish-1.1.5.jar
mystical_pumpkins-0.3.0.jar
neapolitan-1.16.5-2.1.0.jar
Orcinus-Caves-1.0.0.jar
oreganized-1.16.4-0.5.0-beta.jar
OuterEnd-0.2.13.jar
Peculiars-1.16.4-1.1.0.jar
performant-1.16.2-5-3.66m.jar
personality-1.16.5-1.0.2.jar
Placebo-1.16.4-4.5.0.jar
Quark-r2.4-312.jar
QuarkOddities-1.16.3.jar
rats-7.2.0-1.16.5.jar
repurposed_structures-1.16.5-2.7.5-forge.jar
sapience-1.16.4-1.1.1.jar
savageandravage-1.16.5-3.1.0.jar
shutupexperimentalsettings-1.0.3.jar
sodium-forge-2.2.jar
structurize-0.13.177-ALPHA-universal.jar
tetra-1.16.5-3.11.1.jar
tetranomicon-1.3.jar
theoneprobe-1.16-3.1.4.jar
upgrade_aquatic-1.16.5-3.1.0.jar
YungsApi-1.16.4-Forge-6.jar
YungsExtras-Forge-1.16.4-1.0.jar
### Additional Information
Provide any additional information or context which may be relevant to the issue. If you have none to add, you can remove this section.

**Comment by StrangerSon71** [comment]
I'm a idiot, forgot to remove performant.
