### ISSUE TITLE
Game Freeze w/ CTM Mod

### ISSUE THREAD

**Issue by WenXin20** [spoorn/sodium-forge#35]
### Reproduction Steps
1. Install the [CTM](https://www.curseforge.com/minecraft/mc-mods/ctm) mod.
2. Apply the [MC Connected CTM](https://www.curseforge.com/minecraft/texture-packs/mc-connected-ctm) pack.
3. Place down a Chiseled Stone Brick block.
4. Game Freezes.

### Crash Report File
- Not generated.

### [Optional] Server/Client logs
```
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ArrayIndexOutOfBoundsException: 6063
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.jellysquid.mods.sodium.client.world.WorldSlice.func_180495_p(WorldSlice.java:233)
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at team.chisel.ctm.client.util.RegionCache.func_180495_p(RegionCache.java:80)
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at team.chisel.ctm.client.texture.ctx.TextureContextPillar.<init>(TextureContextPillar.java:152)
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at team.chisel.ctm.client.texture.type.TextureTypePillar.getBlockRenderContext(TextureTypePillar.java:25)
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at team.chisel.ctm.client.texture.type.TextureTypePillar.getBlockRenderContext(TextureTypePillar.java:14)
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at team.chisel.ctm.api.util.RenderContextList.<init>(RenderContextList.java:43)
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at team.chisel.ctm.client.state.CTMContext.getContextList(CTMContext.java:34)
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at team.chisel.ctm.client.model.AbstractCTMBakedModel.getQuads(AbstractCTMBakedModel.java:173)
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:68)
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderContext.renderBlock(ChunkRenderContext.java:44)
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:111)
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:343)
[17:06:30] [Chunk Render Task Executor #3/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)
```

### Mods list
- [`CTM v1.1.2.6`](https://www.curseforge.com/minecraft/mc-mods/ctm)
- `Sodium Reforged v2.2`

### Additional Information
- The game freezes as soon as any block is placed using the Pillar texture type from the ctm mod.

**Comment by spoorn** [comment]
Should be fixed in the next release, looks like it's the same issue as https://github.com/CaffeineMC/sodium-fabric/pull/581

**Comment by WenXin20** [comment]
Thanks!
