### ISSUE TITLE
Latest dev version from repo is crashing

### ISSUE THREAD

**Issue by YouYouTheBoxx** [spoorn/sodium-forge#76]
Just load any world while the sodium-reforged mod is there!

**Sadly there is nothing more than that to debug**
java.lang.NullPointerException: Unexpected error
	at net.minecraft.util.math.vector.Matrix4f.multiplyBackward(Matrix4f.java:638) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:sodium.mixins.json:core.matrix.MixinMatrix4f,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.shader.ChunkProgram.setup(ChunkProgram.java:56) ~[?:2.9.1+rev.df076f9-dirty] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.shader.ChunkRenderShaderBackend.begin(ChunkRenderShaderBackend.java:68) ~[?:2.9.1+rev.df076f9-dirty] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.renderLayer(ChunkRenderManager.java:442) ~[?:2.9.1+rev.df076f9-dirty] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:256) ~[?:2.9.1+rev.df076f9-dirty] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.WorldRenderer.func_228441_a_(WorldRenderer.java:6175) ~[?:?]

**Comment by spoorn** [comment]
What version of Forge are you running?  And what Java version

**Comment by YouYouTheBoxx** [comment]
I'm running forge-1.16.5-36.1.31 & jdk-15.0.2.7-openj9

**Comment by Luminatrixx** [comment]
> What version of Forge are you running? And what Java version

I'm running forge-1.16.5-36.1.31 & jdk-15.0.2.7-openj9 (does the same with jre1.8.0_291 & jdk-15)

**Comment by Luminatrixx** [comment]
it was because i was using 'vanilla' shaders which were not compatible with sodium bcz sodium does his own shaders sadly :(
